window.QUESTION_CARDS = [
  'Que cor combina com sua palavra? Por quê?',
  'Qual emoji representa melhor sua palavra? Explique a escolha.',
  'Isso combina mais com calma ou caos?',
  'Você associa isso mais ao dia ou à noite?',
  'Em que tipo de lugar você esperaria encontrar isso?',
  'Qual seria a maior vantagem disso?',
  'Qual seria o maior ponto fraco disso?',
  'Isso parece mais simples ou complexo? Por quê?',
  'Você descreveria isso como discreto ou chamativo?',
  'Isso combina mais com proteção ou ataque?',
  'Que tipo de pessoa se interessaria por isso?',
  'Você confiaria nisso num momento de perigo?',
  'Qual sentimento sua palavra desperta?',
  'Isso combina mais com uma aventura ou com uma rotina tranquila?',
  'Você associa isso mais à inteligência ou à força?',
  'Isso seria mais útil sozinho ou acompanhado?',
  'Se isso fosse uma música, seria agitada ou tranquila?',
  'Que gesto você faria para representar sua palavra?',
  'Qual detalhe diferencia sua palavra de coisas parecidas?',
  'Isso depende mais de habilidade ou de sorte?',
  'Isso combina mais com o passado ou com o futuro?',
  'Você diria que isso é comum ou raro?',
  'Sua palavra lembra algo natural ou algo criado por alguém?',
  'Qual seria uma boa comparação para explicar isso?',
  'Em que situação isso chamaria a atenção de todo mundo?',
  'Isso parece mais previsível ou surpreendente?',
  'Qual seria um bom oposto da sua palavra?',
  'Que som você associa à sua palavra?',
  'Você associa isso mais à velocidade ou à resistência?',
  'Isso combina mais com uma pessoa jovem ou experiente?',
  'Qual seria a primeira coisa que alguém notaria nisso?',
  'Você acha que isso exige cuidado? Por quê?',
  'Isso combina mais com liderança ou com apoio?',
  'Que tipo de problema isso poderia resolver?',
  'Que tipo de problema isso poderia causar?',
  'Isso lembra algo pequeno ou algo grande?',
  'Você associa isso mais a regras ou a improviso?',
  'Qual seria uma boa ocasião para falar sobre isso?',
  'Isso parece fácil ou difícil de entender? Por quê?',
  'Você associa isso mais a tecnologia ou a tradição?',
  'Que característica você destacaria numa recomendação sobre isso?',
  'Qual seria uma crítica possível à sua palavra?',
  'Se isso fosse um clima, seria ensolarado, chuvoso ou tempestuoso?',
  'Isso combina mais com uma equipe ou com uma atuação individual?',
  'Você associa isso mais a humor ou a tensão?',
  'Que outra coisa do mesmo tema lembra sua palavra, sem dizer nenhuma das duas?',
  'Se você pudesse mudar uma característica disso, qual seria?',
  'Dê duas pistas sobre sua palavra: uma bem ampla e outra mais específica.'
];
